services:
  - type: web
    name: amadurs-invoices
    env: python
    region: frankfurt
    plan: starter
    buildCommand: buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --threads=4 --timeout=120
    healthCheckPath: /healthz
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATA_DIR
        value: /opt/render/project/src/data
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 5
